version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: gesdoc_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password
      POSTGRES_DB: gesdoc_train
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
