version: "3.9"

services:
  postgres:
    build: .
    container_name: gesdoc_postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - gesdoc_data:/var/lib/postgresql/data

volumes:
  gesdoc_data:
