version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: gesdoc_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gesdoc_train
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gesdoc-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: gesdoc_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gesdoc.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - gesdoc-net

networks:
  gesdoc-net:
