version: "3.9"

services:
  fastapi:
    build: ./repo-api/backend
    container_name: gesdoc_fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/gesdoc_train
    depends_on:
      - postgres
    networks:
      - gesdoc-net

  postgres:
    image: postgres:15
    container_name: gesdoc_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gesdoc_train
    ports:
      - "5432:5432"
    volumes:
      - ./repo-database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./repo-database/postgres-data:/var/lib/postgresql/data
    networks:
      - gesdoc-net

networks:
  gesdoc-net:
